---
title: "eds-221-day-10-tasks"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
```

```{r}
meteorological <- read_csv(here("data", "ntl20_v6.csv"), na = "-999")

ice_duration <- read_csv(here("data", "ntl33_v7.csv"), na = "-999")
```

```{r}

ggplot(ice_duration, aes(ice_duration, color = lakeid)) +
  geom_boxplot()
```

```{r}
mean_ice <- ice_duration %>% 
  group_by(year4) %>% 
  summarise(mean_ice = mean(ice_duration))

```

```{r}
ggplot(mean_ice, aes(year4, mean_ice)) +
  geom_point()
```

there seems to be a negative correlation between years and mean ice duration.

```{r}
air_temp <- meteorological %>% 
  filter(month %in% c(12,1,2)) %>% 
  group_by(year4) %>% 
  summarise(mean_air = mean(ave_air_temp_adjusted))
```

```{r}
ggplot(air_temp, aes(x = year4, y = mean_air)) +
  geom_point()
```

there seems to be a slight positive correlation between year and mean air temperature.

```{r}
combine_air_ice <- full_join(air_temp, mean_ice)
```

```{r}
ggplot(combine_air_ice, aes(mean_ice, mean_air)) +
  geom_point()
```

there seems to be a negative correlation between mean ice duration and mean air temperature.

```{r}
subset_ice_duration <- ice_duration %>% 
  filter(year4 >= 1970) %>% 
  lubridate::ymd(ice_off)
```
